# Generated by Django 2.2.3 on 2019-07-16 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_title', models.CharField(help_text='Enter title for snippet of code', max_length=200)),
                ('snippet_code', models.TextField(help_text='Enter the snippet code')),
                ('snippet_lang', models.CharField(help_text='Enter the language for snippet of code (i.e. Python, Java, C#, Ruby, etc...)', max_length=100)),
                ('snippet_description', models.TextField(help_text='Enter a docstring to describe the snippet of code.', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
