# Generated by Django 2.2.3 on 2019-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='snippet_description',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='snippet_lang',
        ),
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a docstring to describe the snippet of code.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='languages',
            field=models.CharField(choices=[('python', 'python'), ('js', 'js'), ('html', 'html'), ('lua', 'lua'), ('css', 'css'), ('clike', 'clike'), ('markup', 'markup'), ('html', 'html'), ('bash', 'bash'), ('django', 'django'), ('go', 'go'), ('json', 'json'), ('http', 'http'), ('php', 'php'), ('ruby', 'ruby'), ('sas', 'sas'), ('sass', 'sass'), ('scss', 'scss'), ('sql', 'sql')], default='html', max_length=5),
        ),
    ]
