# Generated by Django 2.2.3 on 2019-07-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190719_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='languages',
            field=models.CharField(choices=[('python', 'python'), ('js', 'js'), ('html', 'html'), ('lua', 'lua'), ('css', 'css'), ('clike', 'clike'), ('markup', 'markup'), ('html', 'html'), ('bash', 'bash'), ('django', 'django'), ('go', 'go'), ('json', 'json'), ('http', 'http'), ('php', 'php'), ('ruby', 'ruby'), ('sas', 'sas'), ('sass', 'sass'), ('scss', 'scss'), ('sql', 'sql')], default='html', max_length=7),
        ),
    ]
