# Generated by Django 2.2.3 on 2019-08-19 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20190818_2318'),
        ('auth', '0011_update_proxy_permissions'),
        ('registration', '0005_auto_20190818_2318'),
        ('social_django', '0009_auto_20190818_2318'),
        ('core', '0004_auto_20190720_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
